spring:
  profiles:
    active:
    - dev
    
---

spring:
  profiles: dev
  application:
    name:  microservicecloud-config-lang-dev

---

spring:
  profiles: test
  application:
    name:  microservicecloud-config-lang-test

 

